name: Cypress Tests
run-name: ${{ github.actor }} is testing E2E tests 🚀
on: [push]
jobs:
  Run-Cypress-E2E-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        run: sudo apt install nodejs

      - name: Intall dependencies
        run: npm install

      - name: Run cypress test
        run: npm run cy:run